apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-issues-data
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/github-issues-data
