apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-issues-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /mnt/github-issues-data 
    server: 10.233.64.91
  persistentVolumeReclaimPolicy: Retain
