apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol
  labels:
    type: nfs
spec:
  storageClassName: default-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/nfs/vol1
