apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/simple
